# Generated by Django 4.2.11 on 2024-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_posts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
