# Generated by Django 3.2.10 on 2024-03-27 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_account_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
