# Generated by Django 4.2.11 on 2024-03-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_ceated_at_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
